name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Delete all the binary junk
          rm -rf build
          rm -rf resources
          rm -rf void_icons
          rm -rf scripts/appimage
          find . -name "*.exe" -type f -delete
          find . -name "*.ico" -type f -delete
          find . -name "*.icns" -type f -delete
          find . -name "*.png" -type f -delete
          find . -name "*.bmp" -type f -delete
          
          # 2. START A FRESH REPO (This wipes the binary history)
          rm -rf .git
          git init
          git config --global user.email "bot@neptunium.ai"
          git config --global user.name "Neptunium Bot"
          git checkout -b main
          git add .
          git commit -m "Fresh clean build for Hugging Face"
          
          # 3. Force push this brand new "clean" history
          git push --force https://jessecodesometimes:$HF_TOKEN@huggingface.co/spaces/jessecodesometimes/Neptunium main
